server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://mysql-container:3306/finance
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
        default_batch_fetch_size: 1000
  #    open-in-view: false

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true